-- Do not edit.  Generated by cheby 1.6.0rc1 using these options:
--  --gen-hdl=dbg_xwrc_board_kasli_regs.vhd -i dbg_xwrc_board_kasli.cheby
-- Generated on Tue Dec 17 12:48:00 2024 by roliveira


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package dbg_xwrc_board_kasli_regs_pkg is
  type t_dbg_wrpc_kasli_regs_master_out is record
    DEBUG_1          : std_logic_vector(31 downto 0);
    DEBUG_2          : std_logic_vector(31 downto 0);
    DEBUG_3          : std_logic_vector(31 downto 0);
    DEBUG_4          : std_logic_vector(31 downto 0);
    DEBUG_5          : std_logic_vector(31 downto 0);
    DEBUG_6          : std_logic_vector(31 downto 0);
    DBG_BASE_WDIAGS_USR : std_logic_vector(31 downto 0);
    DBG_BASE_UART    : std_logic_vector(31 downto 0);
    DBG_CONS_UART_BAUDRATE : std_logic_vector(31 downto 0);
    DBG_UART_REG_BCR : std_logic_vector(31 downto 0);
  end record t_dbg_wrpc_kasli_regs_master_out;
  subtype t_dbg_wrpc_kasli_regs_slave_in is t_dbg_wrpc_kasli_regs_master_out;

  type t_dbg_wrpc_kasli_regs_slave_out is record
    DBG_MEM_SIZE     : std_logic_vector(31 downto 0);
    DBG_OFFSET_BYTES : std_logic_vector(31 downto 0);
    DBG_HARD_CODE_REG_IN : std_logic_vector(31 downto 0);
  end record t_dbg_wrpc_kasli_regs_slave_out;
  subtype t_dbg_wrpc_kasli_regs_master_in is t_dbg_wrpc_kasli_regs_slave_out;

end dbg_xwrc_board_kasli_regs_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.dbg_xwrc_board_kasli_regs_pkg.all;

entity dbg_xwrc_board_kasli_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_cyc_i             : in    std_logic;
    wb_stb_i             : in    std_logic;
    wb_adr_i             : in    std_logic_vector(5 downto 2);
    wb_sel_i             : in    std_logic_vector(3 downto 0);
    wb_we_i              : in    std_logic;
    wb_dat_i             : in    std_logic_vector(31 downto 0);
    wb_ack_o             : out   std_logic;
    wb_err_o             : out   std_logic;
    wb_rty_o             : out   std_logic;
    wb_stall_o           : out   std_logic;
    wb_dat_o             : out   std_logic_vector(31 downto 0);
    -- Wires and registers
    dbg_wrpc_kasli_regs_i : in    t_dbg_wrpc_kasli_regs_master_in;
    dbg_wrpc_kasli_regs_o : out   t_dbg_wrpc_kasli_regs_master_out
  );
end dbg_xwrc_board_kasli_regs;

architecture syn of dbg_xwrc_board_kasli_regs is
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal DEBUG_1_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_1_wreq                   : std_logic;
  signal DEBUG_1_wack                   : std_logic;
  signal DEBUG_2_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_2_wreq                   : std_logic;
  signal DEBUG_2_wack                   : std_logic;
  signal DEBUG_3_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_3_wreq                   : std_logic;
  signal DEBUG_3_wack                   : std_logic;
  signal DEBUG_4_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_4_wreq                   : std_logic;
  signal DEBUG_4_wack                   : std_logic;
  signal DEBUG_5_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_5_wreq                   : std_logic;
  signal DEBUG_5_wack                   : std_logic;
  signal DEBUG_6_reg                    : std_logic_vector(31 downto 0);
  signal DEBUG_6_wreq                   : std_logic;
  signal DEBUG_6_wack                   : std_logic;
  signal DBG_BASE_WDIAGS_USR_reg        : std_logic_vector(31 downto 0);
  signal DBG_BASE_WDIAGS_USR_wreq       : std_logic;
  signal DBG_BASE_WDIAGS_USR_wack       : std_logic;
  signal DBG_BASE_UART_reg              : std_logic_vector(31 downto 0);
  signal DBG_BASE_UART_wreq             : std_logic;
  signal DBG_BASE_UART_wack             : std_logic;
  signal DBG_CONS_UART_BAUDRATE_reg     : std_logic_vector(31 downto 0);
  signal DBG_CONS_UART_BAUDRATE_wreq    : std_logic;
  signal DBG_CONS_UART_BAUDRATE_wack    : std_logic;
  signal DBG_UART_REG_BCR_reg           : std_logic_vector(31 downto 0);
  signal DBG_UART_REG_BCR_wreq          : std_logic;
  signal DBG_UART_REG_BCR_wack          : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(5 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  wb_en <= wb_cyc_i and wb_stb_i;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_we_i)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_we_i) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_we_i)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_we_i) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_ack_o <= ack_int;
  wb_stall_o <= not ack_int and wb_en;
  wb_rty_o <= '0';
  wb_err_o <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_dat_o <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
      end if;
    end if;
  end process;

  -- Register DEBUG_1
  dbg_wrpc_kasli_regs_o.DEBUG_1 <= DEBUG_1_reg;
  DEBUG_1_wack <= DEBUG_1_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_1_reg <= "00000000000000000000000000000001";
      else
        if DEBUG_1_wreq = '1' then
          DEBUG_1_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DEBUG_2
  dbg_wrpc_kasli_regs_o.DEBUG_2 <= DEBUG_2_reg;
  DEBUG_2_wack <= DEBUG_2_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_2_reg <= "00000000000000000000000000000010";
      else
        if DEBUG_2_wreq = '1' then
          DEBUG_2_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DEBUG_3
  dbg_wrpc_kasli_regs_o.DEBUG_3 <= DEBUG_3_reg;
  DEBUG_3_wack <= DEBUG_3_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_3_reg <= "00000000000000000000000000000011";
      else
        if DEBUG_3_wreq = '1' then
          DEBUG_3_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DEBUG_4
  dbg_wrpc_kasli_regs_o.DEBUG_4 <= DEBUG_4_reg;
  DEBUG_4_wack <= DEBUG_4_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_4_reg <= "00000000000000000000000000000100";
      else
        if DEBUG_4_wreq = '1' then
          DEBUG_4_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DEBUG_5
  dbg_wrpc_kasli_regs_o.DEBUG_5 <= DEBUG_5_reg;
  DEBUG_5_wack <= DEBUG_5_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_5_reg <= "00000000000000000000000000000101";
      else
        if DEBUG_5_wreq = '1' then
          DEBUG_5_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DEBUG_6
  dbg_wrpc_kasli_regs_o.DEBUG_6 <= DEBUG_6_reg;
  DEBUG_6_wack <= DEBUG_6_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DEBUG_6_reg <= "00000000000000000000000000000110";
      else
        if DEBUG_6_wreq = '1' then
          DEBUG_6_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_BASE_WDIAGS_USR
  dbg_wrpc_kasli_regs_o.DBG_BASE_WDIAGS_USR <= DBG_BASE_WDIAGS_USR_reg;
  DBG_BASE_WDIAGS_USR_wack <= DBG_BASE_WDIAGS_USR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_BASE_WDIAGS_USR_reg <= "00000000000000000000000000000111";
      else
        if DBG_BASE_WDIAGS_USR_wreq = '1' then
          DBG_BASE_WDIAGS_USR_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_BASE_UART
  dbg_wrpc_kasli_regs_o.DBG_BASE_UART <= DBG_BASE_UART_reg;
  DBG_BASE_UART_wack <= DBG_BASE_UART_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_BASE_UART_reg <= "00000000000000000000000000001000";
      else
        if DBG_BASE_UART_wreq = '1' then
          DBG_BASE_UART_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_CONS_UART_BAUDRATE
  dbg_wrpc_kasli_regs_o.DBG_CONS_UART_BAUDRATE <= DBG_CONS_UART_BAUDRATE_reg;
  DBG_CONS_UART_BAUDRATE_wack <= DBG_CONS_UART_BAUDRATE_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_CONS_UART_BAUDRATE_reg <= "00000000000000000000000000001001";
      else
        if DBG_CONS_UART_BAUDRATE_wreq = '1' then
          DBG_CONS_UART_BAUDRATE_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_UART_REG_BCR
  dbg_wrpc_kasli_regs_o.DBG_UART_REG_BCR <= DBG_UART_REG_BCR_reg;
  DBG_UART_REG_BCR_wack <= DBG_UART_REG_BCR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_UART_REG_BCR_reg <= "00000000000000000000000000001010";
      else
        if DBG_UART_REG_BCR_wreq = '1' then
          DBG_UART_REG_BCR_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_MEM_SIZE

  -- Register DBG_OFFSET_BYTES

  -- Register DBG_HARD_CODE_REG_IN

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, DEBUG_1_wack, DEBUG_2_wack, DEBUG_3_wack,
           DEBUG_4_wack, DEBUG_5_wack, DEBUG_6_wack, DBG_BASE_WDIAGS_USR_wack,
           DBG_BASE_UART_wack, DBG_CONS_UART_BAUDRATE_wack,
           DBG_UART_REG_BCR_wack) begin
    DEBUG_1_wreq <= '0';
    DEBUG_2_wreq <= '0';
    DEBUG_3_wreq <= '0';
    DEBUG_4_wreq <= '0';
    DEBUG_5_wreq <= '0';
    DEBUG_6_wreq <= '0';
    DBG_BASE_WDIAGS_USR_wreq <= '0';
    DBG_BASE_UART_wreq <= '0';
    DBG_CONS_UART_BAUDRATE_wreq <= '0';
    DBG_UART_REG_BCR_wreq <= '0';
    case wr_adr_d0(5 downto 2) is
    when "0000" =>
      -- Reg DEBUG_1
      DEBUG_1_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_1_wack;
    when "0001" =>
      -- Reg DEBUG_2
      DEBUG_2_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_2_wack;
    when "0010" =>
      -- Reg DEBUG_3
      DEBUG_3_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_3_wack;
    when "0011" =>
      -- Reg DEBUG_4
      DEBUG_4_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_4_wack;
    when "0100" =>
      -- Reg DEBUG_5
      DEBUG_5_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_5_wack;
    when "0101" =>
      -- Reg DEBUG_6
      DEBUG_6_wreq <= wr_req_d0;
      wr_ack_int <= DEBUG_6_wack;
    when "0110" =>
      -- Reg DBG_BASE_WDIAGS_USR
      DBG_BASE_WDIAGS_USR_wreq <= wr_req_d0;
      wr_ack_int <= DBG_BASE_WDIAGS_USR_wack;
    when "0111" =>
      -- Reg DBG_BASE_UART
      DBG_BASE_UART_wreq <= wr_req_d0;
      wr_ack_int <= DBG_BASE_UART_wack;
    when "1000" =>
      -- Reg DBG_CONS_UART_BAUDRATE
      DBG_CONS_UART_BAUDRATE_wreq <= wr_req_d0;
      wr_ack_int <= DBG_CONS_UART_BAUDRATE_wack;
    when "1001" =>
      -- Reg DBG_UART_REG_BCR
      DBG_UART_REG_BCR_wreq <= wr_req_d0;
      wr_ack_int <= DBG_UART_REG_BCR_wack;
    when "1010" =>
      -- Reg DBG_MEM_SIZE
      wr_ack_int <= wr_req_d0;
    when "1011" =>
      -- Reg DBG_OFFSET_BYTES
      wr_ack_int <= wr_req_d0;
    when "1100" =>
      -- Reg DBG_HARD_CODE_REG_IN
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (wb_adr_i, rd_req_int, DEBUG_1_reg, DEBUG_2_reg, DEBUG_3_reg, DEBUG_4_reg,
           DEBUG_5_reg, DEBUG_6_reg, DBG_BASE_WDIAGS_USR_reg, DBG_BASE_UART_reg,
           DBG_CONS_UART_BAUDRATE_reg, DBG_UART_REG_BCR_reg,
           dbg_wrpc_kasli_regs_i.DBG_MEM_SIZE,
           dbg_wrpc_kasli_regs_i.DBG_OFFSET_BYTES,
           dbg_wrpc_kasli_regs_i.DBG_HARD_CODE_REG_IN) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case wb_adr_i(5 downto 2) is
    when "0000" =>
      -- Reg DEBUG_1
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_1_reg;
    when "0001" =>
      -- Reg DEBUG_2
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_2_reg;
    when "0010" =>
      -- Reg DEBUG_3
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_3_reg;
    when "0011" =>
      -- Reg DEBUG_4
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_4_reg;
    when "0100" =>
      -- Reg DEBUG_5
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_5_reg;
    when "0101" =>
      -- Reg DEBUG_6
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DEBUG_6_reg;
    when "0110" =>
      -- Reg DBG_BASE_WDIAGS_USR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DBG_BASE_WDIAGS_USR_reg;
    when "0111" =>
      -- Reg DBG_BASE_UART
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DBG_BASE_UART_reg;
    when "1000" =>
      -- Reg DBG_CONS_UART_BAUDRATE
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DBG_CONS_UART_BAUDRATE_reg;
    when "1001" =>
      -- Reg DBG_UART_REG_BCR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DBG_UART_REG_BCR_reg;
    when "1010" =>
      -- Reg DBG_MEM_SIZE
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= dbg_wrpc_kasli_regs_i.DBG_MEM_SIZE;
    when "1011" =>
      -- Reg DBG_OFFSET_BYTES
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= dbg_wrpc_kasli_regs_i.DBG_OFFSET_BYTES;
    when "1100" =>
      -- Reg DBG_HARD_CODE_REG_IN
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= dbg_wrpc_kasli_regs_i.DBG_HARD_CODE_REG_IN;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
